entryPoints:
  web:
    address: ":80"
  metrics:
    address: :8080

providers:
  file:
    filename: "/etc/traefik/dynamic_conf.yml"

api:
  dashboard: true

accessLog:
  filePath: "/logs/access.log"

log:
  filePath: "/logs/traefik.log"
  level: DEBUG

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
